Add test for regex in titleBody rule field.
xstefank/wildfly-github-bot pull request #112
Opened 2023-08-03 06:34 UTC by The-Huginn

2023-08-03 06:47 UTC, petrberan requested changes
As I'm writing the test right now as part of the test refactoring, I'm missing a test for a case when the title nor the body hits the titlebody check

I also added test for the case of both title and body hits, just in case

2023-08-03 06:49 UTC, petrberan commented on src/test/java/io/xstefank/wildfly/bot/PROpenedTest.java
> +                    MockedGHPullRequestProcessor.processEmptyPullRequestMock(mocks.pullRequest(1371642823));
```suggestion
                    MockedGHPullRequestProcessor.processEmptyPullRequestMock(mocks.pullRequest(gitHubJson.id()));
```

2023-08-03 06:49 UTC, petrberan commented on src/test/java/io/xstefank/wildfly/bot/PROpenedTest.java
> +                    GHPullRequest mockedPR = mocks.pullRequest(1371642823);
```suggestion
                    GHPullRequest mockedPR = mocks.pullRequest(gitHubJson.id());
```

2023-08-03 06:49 UTC, petrberan commented on src/test/java/io/xstefank/wildfly/bot/PROpenedTest.java
> +                    GHPullRequest mockedPR = mocks.pullRequest(1371642823);
```suggestion
                    GHPullRequest mockedPR = mocks.pullRequest(gitHubJson.id());
```

2023-08-07 09:14 UTC, petrberan commented on src/test/java/io/xstefank/wildfly/bot/PROpenedTest.java
> +    void testTitleBodyCheckTitleRegexOnOpen() throws IOException {
There is a different regex check on EDIT? If not, I would remove the "onOpen" do prevent confusion

2023-08-07 09:14 UTC, petrberan commented on src/test/java/io/xstefank/wildfly/bot/PROpenedTest.java
> +    void testTitleBodyCheckBodyRegexOnOpen() throws IOException {
There is a different regex check on EDIT? If not, I would remove the "onOpen" do prevent confusion

2023-08-07 09:19 UTC, petrberan commented
I would add one failing test. Probably something like `titleBody: non|valid` just to be sure. 

Also, the regex matching is applied only on `titleBody` and not on `title` or `body`?

2023-08-10 09:16 UTC, petrberan commented on src/test/java/io/xstefank/wildfly/bot/PRRuleTitleBodyCheckTest.java
> +                .action(Action.OPENED)
This line shouldn't be needed in any of the tests. The default action is "opened"

2023-08-10 09:17 UTC, petrberan commented on src/test/java/io/xstefank/wildfly/bot/PRRuleTitleBodyCheckTest.java
> +                      enabled: false
Is there a reason for disabling commit format checks? IIRC the #101 stated that checks should be enabled if we don't specifically want them disabled

2023-08-10 09:19 UTC, petrberan commented on src/test/java/io/xstefank/wildfly/bot/PRRuleTitleBodyCheckTest.java
> +        GitHubJson gitHubJson = GitHubJson.builder(VALID_PR_TEMPLATE_JSON)
Here the `GitHubJson gitHubJson = GitHubJson.builder(VALID_PR_TEMPLATE_JSON).build()` should be fine as default JSON description or title doesn't contain words "not" or "valid". And the action is "opened"

2023-08-11 07:35 UTC, xstefank approved these changes
Remove format only changes please, otherwise good

2023-08-11 07:35 UTC, xstefank commented on src/test/java/io/xstefank/wildfly/bot/PRRuleTitleBodyCheckTest.java
> +                """;
for future, try to avoid this kind of changes. You will be showing in blame even if you are not changing anything here.

2023-08-14 08:17 UTC, xstefank approved these changes

2023-08-14 08:17 UTC, merged